db:
  image: postgres:9.4

test:
  build: .
  command: env
  links:
    - db
  volumes:
    - .:/code
  environment:
    - SOAP_PROXY_URL
    - CCH_WSDL
    - CCH_ENTITY
    - CCH_DIVISION
    - CCH_PRODUCT_SKU
